// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package docs

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockDocStoreReader creates a new instance of MockDocStoreReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDocStoreReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDocStoreReader {
	mock := &MockDocStoreReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDocStoreReader is an autogenerated mock type for the DocStoreReader type
type MockDocStoreReader struct {
	mock.Mock
}

type MockDocStoreReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDocStoreReader) EXPECT() *MockDocStoreReader_Expecter {
	return &MockDocStoreReader_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockDocStoreReader
func (_mock *MockDocStoreReader) Get(key string) (string, bool) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (string, bool)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockDocStoreReader_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockDocStoreReader_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *MockDocStoreReader_Expecter) Get(key any) *MockDocStoreReader_Get_Call {
	return &MockDocStoreReader_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockDocStoreReader_Get_Call) Run(run func(key string)) *MockDocStoreReader_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDocStoreReader_Get_Call) Return(s string, b bool) *MockDocStoreReader_Get_Call {
	_c.Call.Return(s, b)
	return _c
}

func (_c *MockDocStoreReader_Get_Call) RunAndReturn(run func(key string) (string, bool)) *MockDocStoreReader_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Keys provides a mock function for the type MockDocStoreReader
func (_mock *MockDocStoreReader) Keys() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Keys")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockDocStoreReader_Keys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Keys'
type MockDocStoreReader_Keys_Call struct {
	*mock.Call
}

// Keys is a helper method to define mock.On call
func (_e *MockDocStoreReader_Expecter) Keys() *MockDocStoreReader_Keys_Call {
	return &MockDocStoreReader_Keys_Call{Call: _e.mock.On("Keys")}
}

func (_c *MockDocStoreReader_Keys_Call) Run(run func()) *MockDocStoreReader_Keys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDocStoreReader_Keys_Call) Return(strings []string) *MockDocStoreReader_Keys_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockDocStoreReader_Keys_Call) RunAndReturn(run func() []string) *MockDocStoreReader_Keys_Call {
	_c.Call.Return(run)
	return _c
}

// Size provides a mock function for the type MockDocStoreReader
func (_mock *MockDocStoreReader) Size() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Size")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockDocStoreReader_Size_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Size'
type MockDocStoreReader_Size_Call struct {
	*mock.Call
}

// Size is a helper method to define mock.On call
func (_e *MockDocStoreReader_Expecter) Size() *MockDocStoreReader_Size_Call {
	return &MockDocStoreReader_Size_Call{Call: _e.mock.On("Size")}
}

func (_c *MockDocStoreReader_Size_Call) Run(run func()) *MockDocStoreReader_Size_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDocStoreReader_Size_Call) Return(n int) *MockDocStoreReader_Size_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockDocStoreReader_Size_Call) RunAndReturn(run func() int) *MockDocStoreReader_Size_Call {
	_c.Call.Return(run)
	return _c
}
